<?php
/**
 * @file
 * Code for the Home Page feature.
 */

include_once 'home_page.features.inc';

/**
 * Displays the grouped value from the display suite view as a short time.
 *
 * This function is called from the views configuration Display Suite | Settings
 * "Group data".
 */
function home_page_ds_date_view($raw_value, $object) {
  $date_object = new DateObject($raw_value, 'UTC');
  $date_object->setTimezone(new DateTimeZone(date_default_timezone()));
  return date_format_date($date_object, 'time');
}

/**
 * Implements hook_ds_views_row_render_entity_alter().
 *
 * If you're grouping by the 'field_event_date' field, don't show it in the
 * rendered content as well.
 */
function home_page_ds_views_row_render_entity_alter(&$content, &$context) {
  // If this view is already grouped by the field_event_date...
  $options
    = isset($context['view']->display[$context['view']->current_display]->display_options['row_options']['grouping_fieldset']['group_field']) ?
    $context['view']->display[$context['view']->current_display]->display_options['row_options']['grouping_fieldset']['group_field'] :
    '';

  if ($options == 'field_data_field_event_date|field_event_date_value') {
    unset($content['field_event_date']);
  }
}
