<?php
/**
 * @file
 * Code for the Events feature.
 */

include_once('os_event.features.inc');

/**
 * Post-render function that adds a fieldset around .
 */
function _os_event_add_fieldset($children, $elements) {
  // Default collapsed
  $collapsed = TRUE;
  $class = array('collapsible', 'collapsed');

  $fieldset['element'] = array(
    '#title' => t('Filter'),
    '#collapsible' => TRUE,
    '#collapsed' => $collapsed,
    '#attributes' => array('class' => $class),
    '#children' => $children,
  );

  $element_children = element_children($elements);
  foreach ($element_children as $input_name) {
    if (isset($elements[$input_name]['#default_value']) && $elements[$input_name]['#default_value'] != $elements[$input_name]['#value']) {
      // Dropdowns.
      if (isset($elements[$input_name]['#options'][$elements[$input_name]['#value']])) {
        $fieldset['element']['#title'] .= '&bull;' . $elements[$input_name]['#options'][$elements[$input_name]['#value']];
      }
      // Inputs.
      else {
        $fieldset['element']['#title'] .= '&bull;' . $elements[$input_name]['#value'];
      }
    }
  }

  return theme('fieldset', $fieldset);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Wraps exposed form elements in a fieldset.
 */
function os_event_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  global $base_url;

  if(isset($form_state['view']->current_display) && $form_state['view']->current_display == 'panel_pane_calendar') {
    // 1. Add fieldset dropdown.
    $form['#post_render'][] = '_os_event_add_fieldset';
    $form['#attached']['js'][] = $base_url . '/misc/form.js';
    $form['#attached']['js'][] = $base_url . '/misc/collapse.js';
  }
}

/**
* Implements hook_fullcalendar_api().
*/
function os_event_fullcalendar_api() {
  return array(
    'api' => fullcalendar_api_version(),
  );
}
/**
* Implements hook_fullcalendar_options_info().
*/
function os_event_fullcalendar_options_info() {
  return array(
    'os_event' => array(
      'js' => TRUE,
      'no_fieldset' => TRUE,
      'weight' => 5,
    ),
  );
}

/**
 * Renders a map link.
 *
 * @param array $field
 * @return string
 */
function os_event_render_map_link($field) {
  $output = '';
  $settings = isset($field['formatter_settings']) ? $field['formatter_settings'] : array();
  $settings += $field['properties']['default'];

  if(isset($field['entity']->field_location['und'][0]['entity']->field_address['und'][0])) {
    $map = $field['entity']->field_location['und'][0]['entity']->field_address['und'][0];
    $address = $map['thoroughfare'] . '+' . $map['postal_code'];
    $output = l($settings['link text'], 'http://maps.google.com?q=' . $address);
  }

  return $output;
}

/**
 * Renders an iCal link.
 *
 * @param array $field
 * @return string
 */
function os_event_render_ical_link($field) {
  $settings = isset($field['formatter_settings']) ? $field['formatter_settings'] : array();
  $settings += $field['properties']['default'];

  $output = l($settings['link text'], 'events/ical/' . $field['entity']->nid . '.ics');

  return $output;
}

/**
 * Implements hook_ds_field_format_summary().
 *
 * Seems to be needed to pull in the summary.
 */
function os_event_ds_field_format_summary($field) {
  return ds_ds_field_format_summary($field);
}

/**
 * Implements hook_ds_field_settings_form().
 *
 * Seems to be needed to pull in the settings form.
 */
function os_event_ds_field_settings_form($field) {
  return ds_ds_field_settings_form($field);
}
