<?php
/**
 * @file
 * Code for the Geek Portland Location feature.
 */

include_once 'geek_portland_location.features.inc';

/**
 * Implements hook_references_dialog_widgets_alter().
 *
 * Makes the "Create" button stick around even if a node is already set.
 * If this issue ever goes anywhere, we might be able to remove this:
 * https://www.drupal.org/node/1946086
 */
function geek_portland_location_references_dialog_widgets_alter(&$widgets) {
  if (isset($widgets['node_reference_autocomplete']['operations']['add']['function'])) {
    $widgets['node_reference_autocomplete']['operations']['add']['function'] = '_geek_portland_location_references_dialog_node_reference_add_link';
  }
}

/**
 * Helper function to ensure the 'Create' button always shows up.
 */
function _geek_portland_location_references_dialog_node_reference_add_link($element, $widget_settings, $field, $instance) {
  $element['#value'] = $element['#default_value'] = FALSE;
  return references_dialog_node_reference_add_link($element, $widget_settings, $field, $instance);
}
